config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :controllers => {:registrations => "registrations", sessions: "sessions"}
  resources :departments, :permission, :role, :user
  get 'home/home' => 'home#home', :as => 'home_page'
  get 'permissions/role_permission_mgmt' => 'permission#role_permission_mgmt', :as => 'role_pref_mgmt'
  post 'permissions/dynamic_mgmt' => 'permission#dynamic_mgmt', :as => 'role_pref_set'
  root 'home#home'

  mount MongodbLogger::Server.new, :at => "/mongodb"

  mount MongodbLogger::Assets.instance, :at => "/mongodb/assets", :as => :mongodb_assets # assets

end

app/models/permission.rb
class Permission
  include Mongoid::Document
  belongs_to :role
  field :name, :type => String
  field :description, :type => String
  field :action, :type => String
  field :subject_class, :type => String
  field :block, :type => String

  validates :name, presence: true
  validates :description, presence: true
  validates :action, presence: true
  validates :subject_class, presence: true
  validates :block, presence: false

  scope :order_by_asc, -> { ascending(:name) }
  scope :order_by_desc, -> { descending(:name) }
end

app/controllers/permission_controller.rb
class PermissionController < ApplicationController
  before_filter :authenticate_user!
  before_filter :validate_authorization!

  def index
    @permissions = Permission.order_by_asc.all
  end

  def show
    @permission = Permission.find(params[:id])
  end

  def new
    @permission = Permission.new
  end

  def edit
    @permission = Permission.find(params[:id])
  end

  def create
    @permission = Permission.new(permission_params)
    if @permission.save
      redirect_to @permission, notice: 'Permission was successfully created.'
    else
      render :new
    end
  end

  def update
    @permission = Permission.find(params[:id])
    if @permission.update_attributes(permission_params)
      redirect_to @permission, notice: 'Permission was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @permission = Permission.find(params[:id])
    if @permission.destroy
      redirect_to permission_index_path, notice: 'Permission was successfully destroyed.'
    else
      render :index
    end
  end

  def role_permission_mgmt
    @roles = Role.order_by_asc.all
    @permission = Permission.order_by_asc.all
  end

  def dynamic_mgmt
    # hs = {}
    # ar= []
    params[:permission].each do |permission_id, role_ar|
      @permission = Permission.where(id: permission_id).update(role_id: role_ar)
      # role_ar.each do |role|
      #   ar.concat([role.to_s])
      # end
      # hs.merge!({permission_id.to_sym => ar.uniq})
    end
    redirect_to role_pref_mgmt_path, notice: 'Updated successfully.'
  end

  private
  def permission_params
    params.require(:permission).permit(:name, :description, :action, :subject_class, :condition, :block)
  end

  def validate_authorization!
    authorize! :manage, Permission
  end
end

app/helpers/permission_helper.rb
module PermissionHelper
end

app/views/permission/edit.html.erb
<h1>Editing Permission</h1>

<ol class="breadcrumb">
  <li><%= link_to 'Dashboard', home_page_path %></li>
  <li><%= link_to ' Permissions', permission_index_path %></li>
  <li class="active">Edit</li>
</ol>
<%= form_for @permission, url:  permission_path, :method => 'put' do |f| %>
    <% if @permission.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@permission.errors.count, "error") %> prohibited this permission from being saved:</h2>

          <ul>
            <% @permission.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-md-4 margin-bottom-15">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>


    <div class="row">
      <div class="col-md-6 margin-bottom-15">
        <%= f.label :description %><br />
        <%= f.text_area :description, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 margin-bottom-15">
        <%= f.label :action %><br />
        <%= f.text_field :action, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 margin-bottom-15">
        <%= f.label :subject_class %><br />
        <%= f.text_field :subject_class, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 margin-bottom-15">
        <%= f.label :block %><br />
        <%= f.text_area :block, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>


    <div class="row templatemo-form-buttons">
      <div class="col-md-12">
        <button type="submit" class="btn btn-primary">Update</button>
        <button type="reset" class="btn btn-default">Reset</button>
      </div>

    </div>
<% end %>

app/views/permission/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Dashboard', home_page_path %></li>
  <li class="active">Permissions</li>
</ol>

<h1>Listing Permission</h1>

<div class="table-responsive">
  Here shows all permissions
  <span style="margin-left: 600px"><%= link_to 'Add Permission', new_permission_path, 'class' => "btn btn-info" %></span><br /><br />
  <table class="table table-striped table-hover table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Action</th>
      <th>subject_class</th>
      <th>Block</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    <% @permissions.each do |permission| %>
        <tr>
          <td><%= permission.name %></td>
          <td><%= permission.description %></td>
          <td><%= permission.action %></td>
          <td><%= permission.subject_class %></td>
          <td><%= permission.block %></td>
          <td><%= link_to 'Show', permission, 'class' => "btn btn-default" %></td>
          <td><%= link_to 'Edit', edit_permission_path(permission), 'class' => "btn btn-default" %></td>
          <td><%= link_to 'Destroy', permission, method: :delete, data: { confirm: 'Are you sure?' }, 'class' => "btn btn-default" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/permission/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Dashboard', home_page_path %></li>
  <li><%= link_to 'Permissions', permission_index_path %></li>
  <li class="active">New</li>
</ol>

<h1>Add new Permission</h1>

<%= form_for @permission, url: permission_index_path, :method => 'post' do |f| %>
    <% if @permission.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@permission.errors.count, "error") %> prohibited this permission from being saved:</h2>

          <ul>
            <% @permission.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-md-4 margin-bottom-15">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>


    <div class="row">
      <div class="col-md-6 margin-bottom-15">
        <%= f.label :description %><br />
        <%= f.text_area :description, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 margin-bottom-15">
        <%= f.label :action %><br />
        <%= f.text_field :action, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 margin-bottom-15">
        <%= f.label :subject_class %><br />
        <%= f.text_field :subject_class, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 margin-bottom-15">
        <%= f.label :block %><br />
        <%= f.text_area :block, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>


    <div class="row templatemo-form-buttons">
      <div class="col-md-12">
        <button type="submit" class="btn btn-primary">Add</button>
        <button type="reset" class="btn btn-default">Reset</button>
      </div>

    </div>
<% end %>

app/views/permission/role_permission_mgmt.html.erb
<h1>Role Permission management</h1>

<%= form_tag role_pref_set_path, :method => 'post' do |f| %>

    <div class="table-responsive">
      Manage permission for roles<br/><br/>
      <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
          <th>#</th>
          <% for role in @roles %>
              <th><%= role.name.camelize %></th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% for permission in @permission %>
            <tr>
              <th><%= permission.description %></th>
              <% for role in @roles %>
                  <% next if role == "" %>
                  <th><%= check_box_tag "permission[#{permission.id}][#{role.id}]", role.id, role.permissions.include?(permission), {:name => "permission[#{permission.id}][]"} %></th>
              <% end %>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>


    <div class="row templatemo-form-buttons">
      <div class="col-md-12">
        <button type="submit" class="btn btn-primary">Update</button>
        <button type="reset" class="btn btn-default">Reset</button>
      </div>
    </div>

<% end %>

app/views/permission/show.html.erb
<h1>Permission Details</h1>

<ol class="breadcrumb">
  <li><%= link_to 'Dashboard', home_page_path %></li>
  <li><%= link_to 'Permissions', permission_index_path %></li>
  <li class="active">Show</li>
</ol>

<div class="list-group">
  <span class="list-group-item">
      <div class="row">
        <div class="col-md-6 margin-bottom-15">
          <label>NAME:</label>
          <span class="form-control-static"><%= @permission.name %></span>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 margin-bottom-15">
          <label>DESCRIPTION:</label>
          <span class="form-control-static"><%= @permission.description %></span>
        </div>
      </div>

     <div class="row">
       <div class="col-md-6 margin-bottom-15">
         <label>ACTION:</label>
         <span class="form-control-static"><%= @permission.action %></span>
       </div>
     </div>

     <div class="row">
       <div class="col-md-6 margin-bottom-15">
         <label>SUBJECT CLASS:</label>
         <span class="form-control-static"><%= @permission.subject_class %></span>
       </div>
     </div>

     <div class="row">
       <div class="col-md-6 margin-bottom-15">
         <label>BLOCK:</label>
         <span class="form-control-static"><%= @permission.block %></span>
       </div>
     </div>
  </span>
</div>