config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :controllers => {:registrations => "registrations", sessions: "sessions"}
  resources :departments, :permission, :role, :user
  get 'home/home' => 'home#home', :as => 'home_page'
  get 'permissions/role_permission_mgmt' => 'permission#role_permission_mgmt', :as => 'role_pref_mgmt'
  post 'permissions/dynamic_mgmt' => 'permission#dynamic_mgmt', :as => 'role_pref_set'
  root 'home#home'

  mount MongodbLogger::Server.new, :at => "/mongodb"

  mount MongodbLogger::Assets.instance, :at => "/mongodb/assets", :as => :mongodb_assets # assets

end

app/models/department.rb
class Department
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String

  validates :name, presence: true
  validates :description, presence: true


  scope :order_by_asc, -> { ascending(:name) }
  scope :order_by_desc, -> { descending(:name) }
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :validate_authorization!

  def index
    @departments = Department.order_by_asc.all
  end

  def show
    @department = Department.find(params[:id])
  end

  def new
    authorize! :create, Department
    @department = Department.new
  end

  def edit
    authorize! :update, Department
    @department = Department.find(params[:id])
  end

  def create
    authorize! :create, Department
    @department = Department.new(department_params)
    if @department.save
        redirect_to @department, notice: 'Department was successfully created.'
      else
        render :new
    end
  end

  def update
    authorize! :update, Department
    @department = Department.find(params[:id])
    if @department.update(department_params)
      redirect_to @department, notice: 'Department was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize! :destroy, Department
    @department = Department.find(params[:id])
    @department.destroy
      redirect_to departments_url, notice: 'Department was successfully destroyed.'
  end

  private
  def department_params
    params.require(:department).permit(:name, :description)
  end

  def validate_authorization!
    authorize! :read, Department
  end

end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<ol class="breadcrumb">
  <li><%= link_to 'Dashboard', home_page_path %></li>
  <li><%= link_to ' Departments', departments_path %></li>
  <li class="active">Edit</li>
</ol>
<%= form_for(@department) do |f| %>
    <% if @department.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

          <ul>
            <% @department.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-md-4 margin-bottom-15">
        <%= f.label :name %><br />
        <%= f.text_field :name, 'class' => "form-control" %>
      </div>
    </div>


    <div class="row">
      <div class="col-md-6 margin-bottom-15">
        <%= f.label :description %><br />
        <%= f.text_area :description, 'class' => "form-control" %>
      </div>
    </div>


    <div class="row templatemo-form-buttons">
      <div class="col-md-12">
        <button type="submit" class="btn btn-primary">Update</button>
        <button type="reset" class="btn btn-default">Reset</button>
      </div>

    </div>
<% end %>

app/views/departments/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Dashboard', home_page_path %></li>
  <li class="active">Departments</li>
</ol>

<h1>Listing departments</h1>

<div class="table-responsive">
  Here shows all departments
  <span style="margin-left: 402px"><%= link_to 'New Department', new_department_path, 'class' => "btn btn-info" if can? :write, Department %></span><br /><br />
  <table class="table table-striped table-hover table-bordered">
    <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Description</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    <% @departments.each do |department| %>
    <tr>
      <td><%=department.name %></td>
      <td><%=department.name %></td>
      <td><%=department.description %></td>
      <td><%= link_to 'Show', department, 'class' => "btn btn-default" %></td>
      <td><%= link_to 'Edit', edit_department_path(department), 'class' => "btn btn-default" %></td>
      <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' }, 'class' => "btn btn-default" %></td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/departments/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Dashboard', home_page_path %></li>
  <li><%= link_to ' Departments', departments_path %></li>
  <li class="active">New</li>
</ol>

<h1>Add new department</h1>

<%= form_for(@department) do |f| %>
    <% if @department.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

          <ul>
            <% @department.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-md-4 margin-bottom-15">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>


    <div class="row">
      <div class="col-md-6 margin-bottom-15">
        <%= f.label :description %><br />
        <%= f.text_area :description, 'class' => "form-control" %>
      </div>
    </div>


    <div class="row templatemo-form-buttons">
      <div class="col-md-12">
        <button type="submit" class="btn btn-primary">Add</button>
        <button type="reset" class="btn btn-default">Reset</button>
      </div>

    </div>
<% end %>

app/views/departments/show.html.erb
<h1>Department Details</h1>

<ol class="breadcrumb">
  <li><%= link_to 'Dashboard', home_page_path %></li>
  <li><%= link_to ' Departments', departments_path %></li>
  <li class="active">Show</li>
</ol>

<div class="list-group">
  <span class="list-group-item">
      <div class="row">
        <div class="col-md-6 margin-bottom-15">
          <label>NAME:</label>
          <span class="form-control-static"><%= @department.name %></span>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 margin-bottom-15">
          <label>DESCRIPTION:</label>
          <span class="form-control-static"><%= @department.description %></span>
        </div>
      </div>
  </span>
</div>