config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :controllers => {:registrations => "registrations", sessions: "sessions"}
  resources :departments, :permission, :role, :user
  get 'home/home' => 'home#home', :as => 'home_page'
  get 'permissions/role_permission_mgmt' => 'permission#role_permission_mgmt', :as => 'role_pref_mgmt'
  post 'permissions/dynamic_mgmt' => 'permission#dynamic_mgmt', :as => 'role_pref_set'
  root 'home#home'

  mount MongodbLogger::Server.new, :at => "/mongodb"

  mount MongodbLogger::Assets.instance, :at => "/mongodb/assets", :as => :mongodb_assets # assets

end

app/models/role.rb
class Role
  include Mongoid::Document
  has_many :users
  has_many :permissions
  field :name, :type => String
  field :description, :type => String


  scope :order_by_asc, -> { ascending(:name) }
  scope :order_by_desc, -> { descending(:name) }
end

app/controllers/role_controller.rb
class RoleController < ApplicationController
  before_filter :authenticate_user!
  before_filter :validate_authorization!

  def index
    @roles = Role.order_by_asc.all
  end

  def show
    @role = Role.find(params[:id])
  end

  def new
    @role = Role.new
  end

  def edit
    @role = Role.find(params[:id])
  end

  def create
    @role = Role.new(role_params)
    if @role.save
      redirect_to @role, notice: 'Role was successfully created.'
    else
      render :new
    end
  end

  def update
    @role = Role.find(params[:id])
    if @role.update_attributes(role_params)
      redirect_to @role, notice: 'Role was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @role = Role.find(params[:id])
    a = 10
    Permission.in({ id: @role.permission_ids }).pull({role_id: @role.id}) unless @role.permission_ids.blank?
    User.in({ id: @role.user_ids }).pull({role_id: @role.id}) unless @role.user_ids.blank?
    @role.destroy
    redirect_to role_index_path, notice: 'Role was successfully destroyed.'
  end

  private
  def role_params
    params.require(:role).permit(:name, :description)
  end

  def validate_authorization!
    authorize! :manage, Role
  end


end

app/helpers/role_helper.rb
module RoleHelper
end

app/views/role/edit.html.erb
<h1>Editing department</h1>

<ol class="breadcrumb">
  <li><%= link_to 'Dashboard', home_page_path %></li>
  <li><%= link_to ' Role', role_index_path %></li>
  <li class="active">Edit</li>
</ol>
<%= form_for @role, url: role_path, :method => 'put', 'role'=>"form", :id=>"templatemo-preferences-form" do |f| %>
    <% if @role.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@role.errors.count, "error") %> prohibited this department from being saved:</h2>

          <ul>
            <% @role.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-md-4 margin-bottom-15">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>


    <div class="row">
      <div class="col-md-6 margin-bottom-15">
        <%= f.label :description %><br />
        <%= f.text_area :description, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>


    <div class="row templatemo-form-buttons">
      <div class="col-md-12">
        <button type="submit" class="btn btn-primary">Update</button>
        <button type="reset" class="btn btn-default">Reset</button>
      </div>

    </div>
<% end %>

app/views/role/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Dashboard', home_page_path %></li>
  <li class="active">Roles</li>
</ol>

<h1>Listing Roles</h1>

<div class="table-responsive">
  Here shows all roles
  <span style="margin-left: 505px"><%= link_to 'New Role', new_role_path, 'class' => "btn btn-info" %></span><br /><br />
  <table class="table table-striped table-hover table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    <% @roles.each do |role| %>
        <tr>
          <td><%=role.name %></td>
          <td><%=role.description %></td>
          <td><%= link_to 'Show', role, 'class' => "btn btn-default" %></td>
          <td><%= link_to 'Edit', edit_role_path(role), 'class' => "btn btn-default" %></td>
          <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }, 'class' => "btn btn-default" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/role/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Dashboard', home_page_path %></li>
  <li><%= link_to ' Roles', departments_path %></li>
  <li class="active">New</li>
</ol>

<h1>Add new Role</h1>

<%= form_for @role, url: role_index_path, :method => 'post' do |f| %>
    <% if @role.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@role.errors.count, "error") %> prohibited this department from being saved:</h2>

          <ul>
            <% @role.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-md-4 margin-bottom-15">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>


    <div class="row">
      <div class="col-md-6 margin-bottom-15">
        <%= f.label :description %><br />
        <%= f.text_area :description, autofocus: true, 'class' => "form-control" %>
      </div>
    </div>


    <div class="row templatemo-form-buttons">
      <div class="col-md-12">
        <button type="submit" class="btn btn-primary">Add</button>
        <button type="reset" class="btn btn-default">Reset</button>
      </div>

    </div>
<% end %>

app/views/role/show.html.erb
<h1>Role Details</h1>

<ol class="breadcrumb">
  <li><%= link_to 'Dashboard', home_page_path %></li>
  <li><%= link_to ' Roles', role_index_path %></li>
  <li class="active">Show</li>
</ol>

<div class="list-group">
  <span class="list-group-item">
      <div class="row">
        <div class="col-md-6 margin-bottom-15">
          <label>NAME:</label>
          <span class="form-control-static"><%= @role.name %></span>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 margin-bottom-15">
          <label>DESCRIPTION:</label>
          <span class="form-control-static"><%= @role.description %></span>
        </div>
      </div>
  </span>
</div>